spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bloodlink_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
